---
 apiVersion: v1
 kind: Service
 metadata:
   name: nodexpose
   labels:
     app: local-nginx-lb
 spec:
   type: NodePort
   ports:
     - port: 80
       nodePort: 30080
   selector:
     app: local-nginx-lb

---
 apiVersion: v1
 kind: Service
 metadata:
   name: python
 spec:
   selector:
     app: local-simple-python
   ports:
     - name: python-app
       port: 8080
       targetPort: 8080

---
 apiVersion: apps/v1beta2
 kind: Deployment
 metadata:
   name: local-simple-python
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: local-simple-python
   template:
     metadata:
       labels:
         app: local-simple-python
     spec:
       containers:
         - name: python
           image: vivekyad4v/local-simple-python:latest
           ports:
             - containerPort: 8080
       imagePullSecrets:
         - name: regsecret

---
 apiVersion: apps/v1beta2
 kind: Deployment
 metadata:
   name: local-nginx-lb
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: local-nginx-lb
   template:
     metadata:
       labels:
         app: local-nginx-lb
     spec:
       containers:
         - name: nginx
           image: vivekyad4v/local-nginx-lb:latest
           ports:
             - containerPort: 80
       imagePullSecrets:
         - name: regsecret

