version: '3.2'

services:
  python:
    build:
      context: ./simple-web
    image: vivekyad4v/local-simple-python:${VERSION}
    restart: always
    deploy:
      replicas: 2
    ports:
      - 8080

  nginx:
    build:
      context: ./nginx
    image: vivekyad4v/local-nginx-lb:${VERSION}
    restart: always
    deploy:
      replicas: 2
    ports:
      - "80:80"

